EscanBE/evermint

- CHANGELOG.md
- x/evm/keeper/grpc_query.go
Refer #2 
> > block height already minus by one in rpc
> >
> > https://github.com/evmos/ethermint/blob/57ed355c985d9f3116aba6aabfa2ee0f3f38e966/rpc/backend/tracing.go#L110-L114
> > 
> > Oh no, so currently it keep minus by one in grpc so actually minus by 2? If calling via API debug_traceTransaction?
> Fixing BlockNumber from [request](https://github.com/evmos/ethermint/blob/57ed355c985d9f3116aba6aabfa2ee0f3f38e966/rpc/backend/tracing.go#L98), no need minus 1
_Originally posted by `mmsqe` in https://github.com/evmos/ethermint/issues/1591#issuecomment-1373363076_
> The `contextHeight` is minus one to get to the state of block beginning, but the block number pass to evm context should not minus one.
_Originally posted by `yihuang` in …
> fix(evm): Correct context block height when trace transaction

- CHANGELOG.md
- rename-chain.sh
Reason: [CHANGELOG.md](https://github.com/EscanBE/evermint/blob/main/CHANGELOG.md) keeps historical changes those patched in Evermint repo and repo URL should not be renamed to GitHub repo of new chain.
> fix(rename-chain): restore files should not be changed after rename chain

- CHANGELOG.md
**This is the first release of Evermint**
- (rename-chain) Enable developers to fork and transform Evermint to their own chain, fully customized. 👉 [Read more](https://github.com/EscanBE/evermint/blob/main/RENAME_CHAIN.md)
- (cli) Allow convert between 0x address and bech32 address, or any custom bech32 HRP: `evmd convert-address evm1sv9m0g7ycejwr3s369km58h5qe7xj77hxrsmsz evmos`
- (rename-chain) [#4](https://github.com/EscanBE/evermint/pull/4) Restore files that should not be changed after rename chain
- (evm) [#3](https://github.com/EscanBE/evermint/pull/3) Correct context block height when trace transaction
- (evm) [#5](https://github.com/EscanBE/evermint/pull/5) Re-calculate base-fee & adjust gas-meter reset behavior when trace transaction/block
The Evermint project is officially …
> chores: prepare release Evermint v12.2.0

- CHANGELOG.md
- README.md
**This is the first release of Evermint**
- (rename-chain) Enable developers to fork and transform Evermint to their own chain, fully customized. 👉 [Read more](https://github.com/EscanBE/evermint/blob/main/RENAME_CHAIN.md)
- (cli) Allow convert between 0x address and bech32 address, or any custom bech32 HRP: `evmd convert-address evm1sv9m0g7ycejwr3s369km58h5qe7xj77hxrsmsz evmos`
- (rename-chain) [#4](https://github.com/EscanBE/evermint/pull/4) Restore files that should not be changed after rename chain
- (evm) [#3](https://github.com/EscanBE/evermint/pull/3) Correct context block height when trace transaction
- (evm) [#5](https://github.com/EscanBE/evermint/pull/5) Re-calculate base-fee & adjust gas-meter reset behavior when trace transaction/block
The Evermint project is officially …
> chores: sync release v12.2.0 into main

- CHANGELOG.md
- cmd/evmd/root.go
- server/util.go
Read details log: `evmd snapshots --help`
Or here:
```text
How to use "evmd snapshot" command:
In this context, we gonna to export snapshot for height 100000
1. Create state-sync snapshot on a running node with "export"
> sudo systemctl stop evmd
> evmd snapshots export --height 100000
You gonna get state-sync snapshot at ".evermint/snapshots/" dir as usual:
> Log: Snapshot created at height 100000, format 3, chunks 10
2. Pack snapshot with "dump":
> evmd snapshots dump 100000 3
You gonna get "100000-3.tar.gz" at current working directory
3. Share to another node or reset data of current node with "unsafe-reset-all"
4. Unsafe-reset the node and unpack snapshot with "load":
> evmd snapshots load 100000-3.tar.gz
5. Then restore app state with "restore":
> evmd snapshots restore 100000 3
You …
```
> feat(store): add local `snapshots` management commands

- CHANGELOG.md
- cmd/evmd/root.go
- server/util.go
> feat(store): add local `snapshots` management commands (backport #12)

- CHANGELOG.md
- cmd/evmd/inspect/block.go
- cmd/evmd/inspect/inspect.go
- cmd/evmd/inspect/latest_block_number.go
- cmd/evmd/root.go
Closes #9 
New commands:
- `inspect latest-block-number`: Get the latest block number persisted in the db
- `inspect block`: Get a specific block or latest block persisted in the db, marshal to JSON and print out
> feat(store): add `inspect` command and sub-commands

- CHANGELOG.md
- app/app.go
Describe: GOV from v0.47 needs this
> fix(gov): setting max metadata length for gov proposals submission

- CHANGELOG.md
- cmd/evmd/root.go
- server/flags/flags.go
Main purpose of this PR is about to change default gas adjustment (cli) to 1.2 to reduce out of gas error during consensus, due to different of context between simulation and actual execution.
> chores(flags): change default gas adjustment to 1.2 and update default value of some flags

- CHANGELOG.md
- cmd/evmd/root.go
This revert a mistake that `DefaultGasAdjustment` is a constants and can not be modified in cosmos-sdk v0.46
> chores(flags): revert set gas adjustment 1.2 made in #23

- CHANGELOG.md
- app/ante/cosmos/min_price.go
- app/ante/cosmos/min_price_test.go
New rules:
- Fee must be empty (compatible with MinGasPrice is zero)
- Or fee must be single element array of EVM-denom
- Otherwise reject
> imp(fee): reject cosmos txs that fee denom is not evm denom

- CHANGELOG.md
- app/ante/cosmos/min_price.go
- app/ante/cosmos/min_price_test.go
> imp(fee): reject cosmos txs that fee denom is not evm denom (backport #37)

- CHANGELOG.md
- client/testnet.go
- cmd/evmd/testnet.go
This PR is kinda a sync code changes in #50 for a bug that does not occurs in the v12.2 release branch
> imp(test): set chain id into client toml during init testnet v12.2

- CHANGELOG.md
- client/testnet.go
- cmd/evmd/testnet.go
Problem: when running `make localnet-remake` (previously: `localnet-start`), the testnet network can not be started due to problem with `--chain-id` flag from sdk v0.47
Context: Evermint already implemented to read chain-id from `client.toml` but cmd `evmd testnet init-files` does not invoke setting `chain-id` into `client.toml` file of nodes
Solution: `evmd testnet init-files` will set chain-id into `client.toml`
> fix(test): set chain-id into client.toml during init testnet

- CHANGELOG.md
- app/ante/evm/fees.go
- app/ante/evm/fees_test.go
> fix: prevent panic when building error message of fee which overflow int64 (backport #59)

- CHANGELOG.md
- integration_test_util/accounts.go
- integration_test_util/types/chain_app_imp_init.go
- rpc/namespaces/ethereum/eth/eth_rpc_it_suite/eth_api_transaction_test.go
- x/evm/keeper/statedb_test.go
- x/evm/types/msg.go
`NewTx` detected wrongly DynamicTx => LegacyTx
This PR aims to fix it.
> fix(evm): fix wrong Ethereum Tx type when convert to `MsgEthereumTx`

- CHANGELOG.md
- indexer/kv_indexer.go
- indexer/kv_indexer_test.go
- integration_test_util/chain_suite.go
- rpc/backend/account_info_test.go
- rpc/backend/backend.go
- rpc/backend/blocks.go
- rpc/backend/blocks_test.go
- rpc/backend/call_tx.go
- rpc/backend/call_tx_test.go
- rpc/backend/chain_info.go
- rpc/backend/chain_info_test.go
- rpc/backend/indexer_test.go
- rpc/backend/mocks/indexer.go
- rpc/backend/node_info_test.go
- rpc/backend/sign_tx_test.go
- rpc/backend/tracing_test.go
- rpc/backend/tx_info.go
- rpc/backend/tx_info_test.go
- server/config/config.go
- server/config/toml.go
- server/flags/flags.go
- server/indexer_cmd.go
- server/indexer_service.go
- server/start.go
- types/indexer.go
> imp(indexer): make EVMTxIndexer mandatory service, starts before Json-RPC

- CHANGELOG.md
- server/indexer_service.go
#96 contains multiple change for main branch.
This PR aims to cherry-pick a small fix that should be applied to v12.2 as well.
> imp(indexer): skip pruned blocks & drop multiple failed-to-index blocks during indexer boot-up process (cherry-pick partially #96)

- CHANGELOG.md
- app/ante/evm/setup_ctx.go
- utils/utils.go
- x/erc20/keeper/ibc_callbacks.go
- x/evm/keeper/grpc_query.go
- x/evm/keeper/grpc_query_test.go
- x/ibc/transfer/keeper/msg_server.go
Problem: tracing txs will run out of gas sometime.
The reason was AnteHandle set gas config to 0 but not in other place where EVM called without setting gas config to zero.
> fix(evm): general use zero gas config for EVM exec

- CHANGELOG.md
- go.mod
- go.sum
For more information:
- [ASA-2024-007](https://github.com/cosmos/ibc-go/security/advisories/GHSA-j496-crgh-34mx)
- [ibc-go v6.3.0 release log](https://github.com/cosmos/ibc-go/releases/tag/v6.3.0)
> fix(deps): bumps ibc-go to v6.3.0 which include patch for ASA-2024-007

- CHANGELOG.md
- go.mod
- go.sum
For more information:
- [ASA-2024-007](https://github.com/cosmos/ibc-go/security/advisories/GHSA-j496-crgh-34mx)
- [ibc-go v7.4.0 release log](https://github.com/cosmos/ibc-go/releases/tag/v7.4.0)
> fix(deps): bumps ibc-go to v7.4.0 which include patch for ASA-2024-007

- CHANGELOG.md
- app/ante/evm/eth.go
- app/ante/evm/eth_test.go
- app/ante/evm/fees.go
- app/ante/evm/fees_test.go
- app/ante/evm/setup_ctx.go
- app/ante/evm/signverify_test.go
- app/ante/evm/sigverify.go
- app/ante/handler_options.go
To simplify coding business logic, add an ante `SingleEthTxDecorator` to check & allow one and only one Ethereum Tx per tx execution.
> imp(evm): allow one and only one Ethereum Tx per tx execution

- CHANGELOG.md
- app/ante/evm/interfaces.go
- app/ante/evm/setup_ctx.go
- rpc/backend/backend_suite_test.go
- rpc/backend/blocks.go
- rpc/backend/tx_info.go
- utils/utils.go
- x/evm/keeper/abci.go
- x/evm/keeper/grpc_query.go
- x/evm/keeper/keeper.go
- x/evm/keeper/msg_server.go
- x/evm/keeper/state_transition.go
- x/evm/types/key.go
Closes: #91
This PR contains:
- Fix block bloom computation:
- Add new transient store to store tx receipt, use it to compute block bloom at the end of block
- Deprecate legacy block bloom logic and transient store
- Fix receipt bloom computation
- Adjust some transient store call to fix some minor issue
> fix(evm): correct block bloom, receipt bloom computation and some other minor issues of transient data

- CHANGELOG.md
- integration_test_util/chain_suite.go
- rpc/apis.go
- rpc/backend/backend.go
- rpc/backend/backend_suite_test.go
- rpc/backend/call_tx.go
- rpc/backend/call_tx_test.go
- rpc/backend/node_info.go
- rpc/backend/sign_tx.go
- server/json_rpc.go
This PR contains:
- Fix broken testes caused by new flag `--allow-insecure-unlock` introduced in #142
- Minor refactor RPC backend relates to the `allow unprotected txs` option
> fix(rpc): fix broken tests caused by `--allow-insecure-unlock` and minor refactor RPC backend

- CHANGELOG.md
- app/app.go
- app/encoding.go
- app/upgrades/types.go
- ethereum/eip712/eip712_test.go
- rpc/backend/blocks.go
- rpc/backend/blocks_test.go
- rpc/namespaces/ethereum/eth/filters/api.go
- rpc/types/utils.go
- x/evm/keeper/keeper.go
- x/evm/types/msg.go
- x/evm/types/params_test.go
This PR contains:
- Breaking change!!!: bloom emits at `x/evm.EndBlocker` now emits
- Hex of bloom if not empty
- Empty string if bloom is empty
- FIlter system will now returns block bloom along with eth block result
> imp(evm): improve how block bloom emitted and include bloom to block returned by subscription to filter system

- CHANGELOG.md
- app/ante/evm/eth.go
- app/ante/evm/eth_test.go
- app/ante/evm/interfaces.go
- app/ante/evm/setup_ctx.go
- app/ante/evm/setup_ctx_test.go
- app/ante/handler_options.go
- x/erc20/keeper/evm_test.go
- x/erc20/keeper/utils_test.go
- x/evm/handler_test.go
- x/evm/keeper/keeper.go
- x/evm/keeper/msg_server.go
- x/evm/keeper/msg_server_test.go
- x/evm/keeper/state_transition.go
- x/evm/types/key.go
Closes: #152
Adjustment:
- *KEEP:* Nonce still increased by AnteHandle, so if tx fails, the sender nonce still be increased anyway.
- *ADDED:* After nonce increased by AnteHandle, a transient flag will bet set to indicate the sender nonce was increased by AnteHandle
- *ADDED:* When `msg_server` handles the message execution, it will check the flag, if the flag indicate the sender nonce was increased by AnteHandle, it **subtract** the nonce by 1 and reset the flag
- *CHANGED*: nonce increment now follow geth
The flag is needed because the `msg_server.EthereumTx` method will be used for testing purpose and if sender nonce was not increased but it decreased, it no longer correct.
> fix(evm): adjustment logic of how sender nonce increased

- CHANGELOG.md
- app/ante/evm/eth.go
- app/ante/evm/fee_checker.go
- app/ante/evm/fee_checker_test.go
- x/evm/keeper/fees_test.go
- x/evm/utils/ethereum_tx.go
This PR contains:
- Correct effective gas price, which was gone wrong by #160
- Add check only one fee coin is allowed and enforce denom to be EVM denom
> fix(ante): fix `NewDynamicFeeChecker`, correct effective gas price calculation and minor improvement

- CHANGELOG.md
- app/antedl/ante.go
- app/antedl/evmlane/993e_exec_without_error.go
- app/antedl/evmlane/993e_exec_without_error_it_test.go
- integration_test_util/demo/integration_test_demo_contract_test.go
The main purpose is to get rid of bad txs as much as possible, less problem with failed txs.
This decorator only effectives with mempool check (check-tx and re-check-tx context).
For large chains with high through put, can bypass in re-check-tx context (which exec after every commit).
> feat(ante): simulate EVM txs before accept mempool

- CHANGELOG.md
- app/antedl/ante.go
- app/antedl/duallane/01_setup_ctx.go
- app/antedl/duallane/01_setup_ctx_it_test.go
- app/antedl/duallane/07_deduct_fee.go
- app/antedl/duallane/07_deduct_fee_it_test.go
- app/antedl/evmlane/993e_exec_without_error.go
- x/evm/keeper/keeper.go
- x/evm/keeper/state_transition.go
- x/evm/keeper/state_transition_core.go
- x/evm/keeper/state_transition_test.go
- x/evm/types/key.go
Sometime the EVM call from system like `x/erc20`, the sender didn't paid for the gas fee, so we shouldn't refund them.
> fix(evm): prevent refund gas fee if sender wasn't paid for it

- CHANGELOG.md
- x/erc20/keeper/utils_test.go
- x/evm/genesis_test.go
- x/evm/handler_test.go
- x/evm/keeper/abci.go
- x/evm/keeper/grpc_query.go
- x/evm/keeper/grpc_query_test.go
- x/evm/keeper/keeper.go
- x/evm/keeper/keeper_test.go
- x/evm/keeper/msg_server_test.go
- x/evm/keeper/params.go
- x/evm/keeper/state_transition.go
- x/evm/keeper/state_transition_test.go
- x/evm/keeper/statedb.go
- x/evm/keeper/statedb_test.go
- x/evm/types/key.go
- x/evm/types/storage.go
According to Ethereum, current block hash + 255 historical block hash are supported by `GetHashFn`.
This PR introduce new store to persist block hash into store, the most recent 256 records are kept and `GetHashFn` retrieves directly from here.
> fix(evm): support 256 blocks for `GetHashFn`

- CHANGELOG.md
- app/keepers/keepers.go
Staking hooks was set by a defer function so it not available in some keepers which take `x/staking` keeper as struct, like `x/cpc`.
> fix(app): fix staking hooks not available in some keepers

- CHANGELOG.md
- constants/constants.go
- rename_chain/main.go
Since the very first native module of Evermint introduced in https://github.com/EscanBE/evermint/pull/144, the feature `rename-chain` was broken because some proto issue.
This PR aims to fix it and another mis-replacement of external forks which contains word `evermint`.
Users who uses v0.47 only need to cherry-pick this commit [14fd8ab5d4c45fd8a7517b4f6b5a8da5ac241a62](https://github.com/EscanBE/evermint/commit/14fd8ab5d4c45fd8a7517b4f6b5a8da5ac241a62)
> fix(rename-chain): Fix broken feature rename-chain

- CHANGELOG.md
- x/cpc/types/constants.go
- x/evm/keeper/grpc_query.go
Some UI like Metamask when add ERC-20 token, does get code of contract to check if the address is contract or not.
Custom precompiled contract is precompiled contract therefor does not have code so it mistakenly treated the input address (when import token to Metamask) as EoA and result action failed.
This PR returns a pseudo code for custom precompiled contracts, aim to workaround for the issue.
> fix(cpc): add pseudocode when query `eth_getCode` and gRPC query code for custom precompiled contracts
